### ISSUE TITLE
Collecticons-chakra 3.0.1 does not include packaged modules

### ISSUE THREAD

**Issue by oliverroick** [developmentseed/collecticons#22]
The collections-chakra package doesn't include the `dist` directory, which includes the packaged files and type declarations that are referenced in `package.json`

<img width="931" alt="Screenshot 2024-07-05 at 13 44 11" src="https://github.com/developmentseed/collecticons/assets/159510/351b4c49-a825-4ebb-83d8-84e85a1914c0">

**Comment by danielfdsilva** [comment]
Fixed with v3.0.2. https://www.npmjs.com/package/@devseed-ui/collecticons-chakra?activeTab=code

The GH action was missing the build step, going straight to publish 🤦
