### ISSUE TITLE
Remove libxmljs dependency

### ISSUE THREAD

**Issue by dereklieu** [developmentseed/collecticons#8]
`gulp-xml-editor` uses `libxmljs` under the hood, which can break travis builds when node version > 0.12.

There are a few open issues in the libxmljs repo, [here is one](https://github.com/polotek/libxmljs/issues/393).

This is keeping us from using newer node for travis builds in [openroads-analytics](https://github.com/opengovt/openroads-analytics/pull/113), for example.

**Comment by danielfdsilva** [comment]
Fixed in collecticons-processor#3.1.0
